### ISSUE TITLE
Can I use Lora and Lycoris inside segments? Will it work?

### ISSUE THREAD

**Issue by Lemniscatas** [naver-ai/DenseDiffusion#10]

**Comment by YunjiKim** [comment]
can't say for sure but we plan to open the code for any models with self- and cross- attention layers.

**Comment by George0726** [comment]
When upgrading the diffuser version to v0.21.0, it can work well with LoRA. 

Thanks for the Author!

**Comment by YunjiKim** [comment]
oh cool! thank you for sharing!!
