### ISSUE TITLE
question about the detail

### ISSUE THREAD

**Issue by XiaoyuShi97** [naver-ai/DenseDiffusion#11]
Hi, great work and thanks for sharing the code. I have a question about this line. Could you explain a bit why iterate over 77?
https://github.com/naver-ai/DenseDiffusion/blob/a2ba65ae09dcf84fa443fab047a47995671893b5/gradio_app.py#L196

**Comment by YunjiKim** [comment]
it's for updating parts of textual features that are corresponding to object descriptions.
we found that it is helpful when multiple objects are similar such as oven & microwave.

**Comment by XiaoyuShi97** [comment]
If I understand correctly, this implicitly assumes the prompts for each segment keep unchanged in the master/general prompt?

**Comment by YunjiKim** [comment]
we assume object features are mixed in the master prompt, so we replace parts of the original textual features with the ones exclusively encoded from segment texts.
