### ISSUE TITLE
Host the demo on Hugging Face?

### ISSUE THREAD

**Issue by apolinario** [naver-ai/DenseDiffusion#13]
Hi! I love DenseDiffusion, would be amazing to have a demo running on Hugging Face for it 🤗

If you would like to create one, we could provide it with a GPU to run the model (disclosure: I work at Hugging Face)

**Comment by YunjiKim** [comment]
that would be great ..! thanks for the offer !
we were actually preparing to open a demo on Hugging Face but it was on hold since I am updating some parts of code.
how can I contact you when I am ready ?
