### ISSUE TITLE
Question: size of the hidden_states

### ISSUE THREAD

**Issue by momopusheen** [naver-ai/DenseDiffusion#15]
Hi, thanks for your brilliant work!

I have a question about the dimensions of the hidden states in the 'mod_forward' function.

When I use the batch size of 1 (latent size = [1, 4, 64, 64]), the size of hidden_states is [2, 4096, 320] at the first iteration of 'mod_forward'. In standard SD, the size is [1, 4096, 320]. Do you use some special preprocessing leading to the difference?

Thanks a lot!

**Comment by YunjiKim** [comment]
Hi! The batch size is 2 because of the classifier-free guidance!

**Comment by momopusheen** [comment]
Got it! Please accept my gratitude!😊
