### ISSUE TITLE
Would you mind releasing the evaluation code of IoU ?

### ISSUE THREAD

**Issue by momopusheen** [naver-ai/DenseDiffusion#16]
Thanks for your brilliant work!

I wonder that if you mind releasing the evaluation code of IoU. I know that you use yolov7 for semantic segmentation, however there's no label for the test layouts. (in testset_layout.tar.gz). So it's a bit confusing utilizing yolo for quantitive evaluation. 😊

**Comment by frank-xwang** [comment]
Hi, thank you for your great work! I have a similar question regarding how IoU is measured. Is IoU evaluated by measuring the mean IoU between GT and Prediction at the image-level or at the instance-level? If it's at the instance level, suppose there are 2 instances per image, how do you match these 2 instance's ground-truth masks to N model predictions (N might be smaller or larger than 2)? Thank you!

**Comment by YunjiKim** [comment]
Hi, sorry for the late reply!

We followed the approach used by SpaText's authors, which is more like Recall.
The necessary files for IoU measurement have been added to the repository.

Here are the specific instructions.
1. (If you have already downloaded this repository,) please additionally download [the annotation file](https://github.com/naver-ai/DenseDiffusion/blob/main/dataset/testset_instances.pkl) and [the evaluation code](https://github.com/naver-ai/DenseDiffusion/blob/main/eval_iou.ipynb).
2. Download the YOLOv7-mask code repository from [here](https://github.com/WongKinYiu/yolov7/tree/mask), and the weights of the model from [here](https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7-mask.pt).
3. Move [the evaluation code](https://github.com/naver-ai/DenseDiffusion/blob/main/eval_iou.ipynb) into that folder.

You might run into an error regarding 'nn.Upsample' function, which can be resolved by applying [this solution](https://github.com/WongKinYiu/yolov7/issues/647#issuecomment-1423777996).
If you have any further questions, please feel free to ask me!

**Comment by momopusheen** [comment]
Got it! I'm grateful for your great help! 😊
