### ISSUE TITLE
skip downloading the model from the huggingface

### ISSUE THREAD

**Issue by chenkai-666** [naver-ai/DenseDiffusion#3]
Is there any way to skip downloading the model from the huggingface and directly load the local model like SD webui

![image](https://github.com/naver-ai/DenseDiffusion/assets/81290054/82c8438f-9f90-4012-a7b9-d6764345004e)

**Comment by YunjiKim** [comment]
If you already have the corresponding model, change [this line](https://github.com/naver-ai/DenseDiffusion/blob/main/gradio_app.py#L68) with the path of that model.
