### ISSUE TITLE
Question: Requirements

### ISSUE THREAD

**Issue by jwooldridge234** [naver-ai/DenseDiffusion#5]
Not an issue, just a question- what are the VRAM/RAM requirements for running this method? I have an 8GB GPU/16GB RAM macbook and it said it attempted to allocate 15.8GB. I added attention slicing to the pipeline but it didn't seem to make any difference. Is there any potential for lowering the requirements with this method?

**Comment by YunjiKim** [comment]
hmm.. have you tried with a smaller batch size?

**Comment by jwooldridge234** [comment]
I haven't- where's that set in the code? I see it set in the forward function on line 80, but it never seems to get used

**Comment by jwooldridge234** [comment]
Nevermind, I missed the number of samples in the interface- thanks!
